// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go-lo.proto

package golo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Context struct {
	JobName              string   `protobuf:"bytes,1,opt,name=jobName,proto3" json:"jobName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e939d8b2166d8ec, []int{0}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

type ResponseTag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseTag) Reset()         { *m = ResponseTag{} }
func (m *ResponseTag) String() string { return proto.CompactTextString(m) }
func (*ResponseTag) ProtoMessage()    {}
func (*ResponseTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e939d8b2166d8ec, []int{1}
}

func (m *ResponseTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseTag.Unmarshal(m, b)
}
func (m *ResponseTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseTag.Marshal(b, m, deterministic)
}
func (m *ResponseTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseTag.Merge(m, src)
}
func (m *ResponseTag) XXX_Size() int {
	return xxx_messageInfo_ResponseTag.Size(m)
}
func (m *ResponseTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseTag.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseTag proto.InternalMessageInfo

func (m *ResponseTag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ResponseTag) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Response struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	JobName              string         `protobuf:"bytes,2,opt,name=jobName,proto3" json:"jobName,omitempty"`
	Error                bool           `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	Duration             uint64         `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Output               string         `protobuf:"bytes,5,opt,name=output,proto3" json:"output,omitempty"`
	Tags                 []*ResponseTag `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_7e939d8b2166d8ec, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Response) GetJobName() string {
	if m != nil {
		return m.JobName
	}
	return ""
}

func (m *Response) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Response) GetDuration() uint64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *Response) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *Response) GetTags() []*ResponseTag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterType((*Context)(nil), "golo.Context")
	proto.RegisterType((*ResponseTag)(nil), "golo.ResponseTag")
	proto.RegisterType((*Response)(nil), "golo.Response")
}

func init() { proto.RegisterFile("go-lo.proto", fileDescriptor_7e939d8b2166d8ec) }

var fileDescriptor_7e939d8b2166d8ec = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xdd, 0x4a, 0xc4, 0x30,
	0x10, 0x85, 0x4d, 0xdb, 0x6d, 0xeb, 0x14, 0x17, 0x1d, 0x44, 0xc2, 0x5e, 0x95, 0x8a, 0x50, 0x04,
	0x0b, 0xae, 0xf8, 0x04, 0xde, 0x79, 0xe1, 0x45, 0xd8, 0x17, 0x48, 0xe9, 0x10, 0xaa, 0xb5, 0x53,
	0xd2, 0x54, 0xf4, 0x81, 0x7c, 0x4f, 0xe9, 0xcf, 0xca, 0xf6, 0x2e, 0x5f, 0x66, 0xce, 0x1c, 0xce,
	0x81, 0xc4, 0xf0, 0x43, 0xc3, 0x45, 0x67, 0xd9, 0x31, 0x06, 0x86, 0x1b, 0xce, 0x6e, 0x21, 0x7a,
	0xe1, 0xd6, 0xd1, 0xb7, 0x43, 0x09, 0xd1, 0x3b, 0x97, 0x6f, 0xfa, 0x93, 0xa4, 0x48, 0x45, 0x7e,
	0xae, 0x8e, 0x98, 0x3d, 0x43, 0xa2, 0xa8, 0xef, 0xb8, 0xed, 0xe9, 0xa0, 0x0d, 0x5e, 0x82, 0xff,
	0x41, 0x3f, 0xcb, 0xd2, 0xf8, 0xc4, 0x6b, 0xd8, 0x7c, 0xe9, 0x66, 0x20, 0xe9, 0x4d, 0x7f, 0x33,
	0x64, 0xbf, 0x02, 0xe2, 0xa3, 0x0e, 0xb7, 0xe0, 0xd5, 0xd5, 0xa2, 0xf1, 0xea, 0xea, 0xd4, 0xcd,
	0x5b, 0xb9, 0x8d, 0xc7, 0xc8, 0x5a, 0xb6, 0xd2, 0x4f, 0x45, 0x1e, 0xab, 0x19, 0x70, 0x07, 0x71,
	0x35, 0x58, 0xed, 0x6a, 0x6e, 0x65, 0x90, 0x8a, 0x3c, 0x50, 0xff, 0x8c, 0x37, 0x10, 0xf2, 0xe0,
	0xba, 0xc1, 0xc9, 0xcd, 0x74, 0x6a, 0x21, 0xbc, 0x83, 0xc0, 0x69, 0xd3, 0xcb, 0x30, 0xf5, 0xf3,
	0x64, 0x7f, 0x55, 0x8c, 0x89, 0x8b, 0x93, 0x24, 0x6a, 0x1a, 0xef, 0x1f, 0xc1, 0x7f, 0xe5, 0x12,
	0xef, 0x21, 0x3a, 0xd8, 0xda, 0x18, 0xb2, 0x78, 0x31, 0xaf, 0x2e, 0xcd, 0xec, 0xb6, 0x6b, 0x65,
	0x76, 0x56, 0x86, 0x53, 0x87, 0x4f, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xb3, 0xc4, 0x4d,
	0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	Trigger(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Response, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) Trigger(ctx context.Context, in *Context, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/golo.Job/Trigger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	Trigger(context.Context, *Context) (*Response, error)
}

// UnimplementedJobServer can be embedded to have forward compatible implementations.
type UnimplementedJobServer struct {
}

func (*UnimplementedJobServer) Trigger(ctx context.Context, req *Context) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trigger not implemented")
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_Trigger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Context)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).Trigger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/golo.Job/Trigger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).Trigger(ctx, req.(*Context))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "golo.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Trigger",
			Handler:    _Job_Trigger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-lo.proto",
}
